name: Deploy Website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-static-site .

    - name: Done!
      run: echo "Your site is built! 🧱"
